//----------------------------------------------------------------------
// WARNING: This file was generated by config2cpp. Do not edit.
//----------------------------------------------------------------------

#include "NFDRSInitConfig.h"





//--------
// Define the singleton object
//--------
NFDRSInitConfig NFDRSInitConfig::s_singleton;


NFDRSInitConfig::NFDRSInitConfig()
{
	m_schema[0] = "1000hr_opts = scope";
	m_schema[1] = "1000hr_opts.adsorptionRate = float";
	m_schema[2] = "1000hr_opts.desorptionRate = float";
	m_schema[3] = "1000hr_opts.maxLocalMoisture = float";
	m_schema[4] = "1000hr_opts.radius = float";
	m_schema[5] = "1000hr_opts.stickDensity = float";
	m_schema[6] = "100hr_opts = scope";
	m_schema[7] = "100hr_opts.adsorptionRate = float";
	m_schema[8] = "100hr_opts.desorptionRate = float";
	m_schema[9] = "100hr_opts.maxLocalMoisture = float";
	m_schema[10] = "100hr_opts.radius = float";
	m_schema[11] = "100hr_opts.stickDensity = float";
	m_schema[12] = "10hr_opts = scope";
	m_schema[13] = "10hr_opts.adsorptionRate = float";
	m_schema[14] = "10hr_opts.desorptionRate = float";
	m_schema[15] = "10hr_opts.maxLocalMoisture = float";
	m_schema[16] = "10hr_opts.radius = float";
	m_schema[17] = "10hr_opts.stickDensity = float";
	m_schema[18] = "1hr_opts = scope";
	m_schema[19] = "1hr_opts.adsorptionRate = float";
	m_schema[20] = "1hr_opts.desorptionRate = float";
	m_schema[21] = "1hr_opts.maxLocalMoisture = float";
	m_schema[22] = "1hr_opts.radius = float";
	m_schema[23] = "1hr_opts.stickDensity = float";
	m_schema[24] = "MXD = int";
	m_schema[25] = "avgAnnualPrecip = float";
	m_schema[26] = "deadFuelMoisture = scope";
	m_schema[27] = "deadFuelMoisture.defaults = scope";
	m_schema[28] = "deadFuelMoisture.defaults.adsorptionRate = float";
	m_schema[29] = "deadFuelMoisture.defaults.desorptionRate = float";
	m_schema[30] = "deadFuelMoisture.defaults.maxLocalMoisture = float";
	m_schema[31] = "deadFuelMoisture.defaults.radius = float";
	m_schema[32] = "deadFuelMoisture.defaults.stickDensity = float";
	m_schema[33] = "fuelModel = string";
	m_schema[34] = "gsi_opts = scope";
	m_schema[35] = "gsi_opts.fuelMoistureMax = int";
	m_schema[36] = "gsi_opts.fuelMoistureMin = int";
	m_schema[37] = "gsi_opts.gsiAveragingDays = int";
	m_schema[38] = "gsi_opts.gsiDayLenMax = int";
	m_schema[39] = "gsi_opts.gsiDayLenMin = int";
	m_schema[40] = "gsi_opts.gsiHerbGreenup = float";
	m_schema[41] = "gsi_opts.gsiMax = float";
	m_schema[42] = "gsi_opts.gsiNumPrecipDays = int";
	m_schema[43] = "gsi_opts.gsiRTPrecipMax = float";
	m_schema[44] = "gsi_opts.gsiRTPrecipMin = float";
	m_schema[45] = "gsi_opts.gsiTminMax = int";
	m_schema[46] = "gsi_opts.gsiTminMin = int";
	m_schema[47] = "gsi_opts.gsiUseRTPrecip = int";
	m_schema[48] = "gsi_opts.gsiUseVpdAvg = int";
	m_schema[49] = "gsi_opts.gsiVpdMax = int";
	m_schema[50] = "gsi_opts.gsiVpdMin = int";
	m_schema[51] = "herb_opts = scope";
	m_schema[52] = "herb_opts.fuelMoistureMax = int";
	m_schema[53] = "herb_opts.fuelMoistureMin = int";
	m_schema[54] = "herb_opts.gsiAveragingDays = int";
	m_schema[55] = "herb_opts.gsiDayLenMax = int";
	m_schema[56] = "herb_opts.gsiDayLenMin = int";
	m_schema[57] = "herb_opts.gsiHerbGreenup = float";
	m_schema[58] = "herb_opts.gsiMax = float";
	m_schema[59] = "herb_opts.gsiNumPrecipDays = int";
	m_schema[60] = "herb_opts.gsiRTPrecipMax = float";
	m_schema[61] = "herb_opts.gsiRTPrecipMin = float";
	m_schema[62] = "herb_opts.gsiTminMax = int";
	m_schema[63] = "herb_opts.gsiTminMin = int";
	m_schema[64] = "herb_opts.gsiUseRTPrecip = int";
	m_schema[65] = "herb_opts.gsiUseVpdAvg = int";
	m_schema[66] = "herb_opts.gsiVpdMax = int";
	m_schema[67] = "herb_opts.gsiVpdMin = int";
	m_schema[68] = "isAnnuals = int";
	m_schema[69] = "kbdiThreshold = int";
	m_schema[70] = "latitude = float";
	m_schema[71] = "liveFuelMoisture = scope";
	m_schema[72] = "liveFuelMoisture.defaults = scope";
	m_schema[73] = "liveFuelMoisture.defaults.fuelMoistureMax = int";
	m_schema[74] = "liveFuelMoisture.defaults.fuelMoistureMin = int";
	m_schema[75] = "liveFuelMoisture.defaults.gsiAveragingDays = int";
	m_schema[76] = "liveFuelMoisture.defaults.gsiDayLenMax = int";
	m_schema[77] = "liveFuelMoisture.defaults.gsiDayLenMin = int";
	m_schema[78] = "liveFuelMoisture.defaults.gsiHerbGreenup = float";
	m_schema[79] = "liveFuelMoisture.defaults.gsiMax = float";
	m_schema[80] = "liveFuelMoisture.defaults.gsiNumPrecipDays = int";
	m_schema[81] = "liveFuelMoisture.defaults.gsiRTPrecipMax = float";
	m_schema[82] = "liveFuelMoisture.defaults.gsiRTPrecipMin = float";
	m_schema[83] = "liveFuelMoisture.defaults.gsiTminMax = int";
	m_schema[84] = "liveFuelMoisture.defaults.gsiTminMin = int";
	m_schema[85] = "liveFuelMoisture.defaults.gsiUseRTPrecip = int";
	m_schema[86] = "liveFuelMoisture.defaults.gsiUseVpdAvg = int";
	m_schema[87] = "liveFuelMoisture.defaults.gsiVpdMax = int";
	m_schema[88] = "liveFuelMoisture.defaults.gsiVpdMin = int";
	m_schema[89] = "maxSC = int";
	m_schema[90] = "obsHour = int";
	m_schema[91] = "slopeClass = int";
	m_schema[92] = "startKBDI = int";
	m_schema[93] = "timeZoneOffset = int";
	m_schema[94] = "useCure = int";
	m_schema[95] = "useLoadTransfer = int";
	m_schema[96] = "woody_opts = scope";
	m_schema[97] = "woody_opts.fuelMoistureMax = int";
	m_schema[98] = "woody_opts.fuelMoistureMin = int";
	m_schema[99] = "woody_opts.gsiAveragingDays = int";
	m_schema[100] = "woody_opts.gsiDayLenMax = int";
	m_schema[101] = "woody_opts.gsiDayLenMin = int";
	m_schema[102] = "woody_opts.gsiHerbGreenup = float";
	m_schema[103] = "woody_opts.gsiMax = float";
	m_schema[104] = "woody_opts.gsiNumPrecipDays = int";
	m_schema[105] = "woody_opts.gsiRTPrecipMax = float";
	m_schema[106] = "woody_opts.gsiRTPrecipMin = float";
	m_schema[107] = "woody_opts.gsiTminMax = int";
	m_schema[108] = "woody_opts.gsiTminMin = int";
	m_schema[109] = "woody_opts.gsiUseRTPrecip = int";
	m_schema[110] = "woody_opts.gsiUseVpdAvg = int";
	m_schema[111] = "woody_opts.gsiVpdMax = int";
	m_schema[112] = "woody_opts.gsiVpdMin = int";
	m_schema[113] = 0;

	m_str << "#Sample NFDRS2016 initialization file\n";
	m_str << "#contains all parameters to initialize an NFSDRS20";
	m_str << "16 object for computation\n";
	m_str << "#used by config2cpp as:\n";
	m_str << "#config2cpp -cfg NFDRSInitSample.txt -class NFDRSI";
	m_str << "nitConfig -singleton\n";
	m_str << "#generates NFDRSInitConfig.cpp and NFDRSInitConfig";
	m_str << ".h, \n";
	m_str << "#these must be copied to RunNFDRS directory to rep";
	m_str << "lace old versions in the project\n";
	m_str << "#\n";
	m_str << "#latitude decimal degrees\n";
	m_str << "latitude = \"47.01\";\n";
	m_str << "#NFDRS2016 fuel model (one of V, W, X, Y, Z)\n";
	m_str << "fuelModel = \"Y\";\n";
	m_str << "#standard NFDRS Slope Class (1 = 0.25%, 2 = 26-40%";
	m_str << ", 3 = 41 - 55%, 4 = 56 - 75%, 5 = 76%+)\n";
	m_str << "slopeClass = \"1\";\n";
	m_str << "#average annual precipitation (inches)\n";
	m_str << "avgAnnualPrecip = \"13.4\";\n";
	m_str << "#load transfer flag, should always be \"1\"\n";
	m_str << "useLoadTransfer = \"1\";\n";
	m_str << "#curing flag, should always be \"1\"\n";
	m_str << "useCure = \"1\";\n";
	m_str << "#annuals flag, 1 = herbs are annuals, 0 = perennia";
	m_str << "l\n";
	m_str << "isAnnuals = \"1\";\n";
	m_str << "#threshold KBDI value, minimum value to have KBDI ";
	m_str << "modify NFDRS Index calculation\n";
	m_str << "kbdiThreshold = \"100\";\n";
	m_str << "# initial KBDI value on Init\n";
	m_str << "startKBDI = \"100\";\n";
	m_str << "# flag to indicate Humid climate\n";
	m_str << "# flag removed  8/26/2023 SB\n";
	m_str << "#isHumid = \"1\";\n";
	m_str << "#MXD added 8/26/2023 SB\n";
	m_str << "#Moisture of Extinction (%), any positive value ot";
	m_str << "her than zero (0) will override fuel model default";
	m_str << " MXD for the fuel model\n";
	m_str << "MXD = \"0\";\n";
	m_str << "# hour when daily observations are reported and GS";
	m_str << "I/Live fuel moistures updated\n";
	m_str << "obsHour = \"13\";\n";
	m_str << "# timeZone offset from UTC, absolutely necessary i";
	m_str << "f FW21 data is Zulu time\n";
	m_str << "timeZoneOffset = \"-6\";\n";
	m_str << "#for maxSC, any positive value other than zero (0)";
	m_str << " will override fuel model default maxSC\n";
	m_str << "maxSC = \"0\";\n";
	m_str << "#\n";
	m_str << "#GSI and Live Fuel Moistures\n";
	m_str << "#\n";
	m_str << "liveFuelMoisture.defaults {\n";
	m_str << "\tgsiMax = \"1.0\";\n";
	m_str << "\tgsiHerbGreenup = \"0.5\";\n";
	m_str << "\tgsiTminMin = \"-2\";\n";
	m_str << "\tgsiTminMax = \"5\";\n";
	m_str << "\tgsiVpdMin = \"900\";\n";
	m_str << "\tgsiVpdMax = \"4100\";\n";
	m_str << "\tgsiDayLenMin = \"36000\";\n";
	m_str << "\tgsiDayLenMax = \"39600\";\n";
	m_str << "\tgsiUseVpdAvg = \"0\";\n";
	m_str << "\tgsiAveragingDays = \"21\";\n";
	m_str << "\tgsiNumPrecipDays = \"30\";\n";
	m_str << "\tgsiRTPrecipMin = \"0.5\";\n";
	m_str << "\tgsiRTPrecipMax = \"1.5\";\n";
	m_str << "\tgsiUseRTPrecip = \"0\";\n";
	m_str << "\tfuelMoistureMax = \"100\";\n";
	m_str << "\tfuelMoistureMin = \"0\";\n";
	m_str << "}\n";
	m_str << "#set any GSI specific options here\n";
	m_str << "gsi_opts {\n";
	m_str << "\t@copyFrom \"liveFuelMoisture.defaults\";\n";
	m_str << "\n";
	m_str << "}\n";
	m_str << "#set any Herb LFM specific options here\n";
	m_str << "herb_opts {\n";
	m_str << "\t@copyFrom \"liveFuelMoisture.defaults\";\n";
	m_str << "\tfuelMoistureMax = \"250\";\n";
	m_str << "\tfuelMoistureMin = \"30\";\n";
	m_str << "}\n";
	m_str << "\n";
	m_str << "#set any Woody LFM specific options here\n";
	m_str << "woody_opts {\n";
	m_str << "\t@copyFrom \"liveFuelMoisture.defaults\";\n";
	m_str << "\tfuelMoistureMax = \"200\";\n";
	m_str << "\tfuelMoistureMin = \"50\";\n";
	m_str << "}\n";
	m_str << "\n";
	m_str << "#Dead Fuel Moisture settings\n";
	m_str << "#1hr, 10 hr, 100hr, 1000hr\n";
	m_str << "deadFuelMoisture.defaults {\n";
	m_str << "#These were previously specific to stick size, sho";
	m_str << "uld always be present\n";
	m_str << "\tradius = \"0.64\";\n";
	m_str << "\tadsorptionRate = \"0.079548303\";\n";
	m_str << "#These were previously defaults in DeadFuelMoistur";
	m_str << "e::initializeParameters()\n";
	m_str << "\tstickDensity = \"0.400\";\n";
	m_str << "\tmaxLocalMoisture = \"0.35\";\n";
	m_str << "\tdesorptionRate = \"0.06\";\n";
	m_str << "}\n";
	m_str << "# 1hr options\n";
	m_str << "1hr_opts {\n";
	m_str << "\t@copyFrom \"deadFuelMoisture.defaults\";\n";
	m_str << "\tradius = \"0.2\";\n";
	m_str << "\tadsorptionRate = \"0.462252733\";\n";
	m_str << "}\n";
	m_str << "# 10hr options\n";
	m_str << "10hr_opts {\n";
	m_str << "\t@copyFrom \"deadFuelMoisture.defaults\";\n";
	m_str << "\tradius = \"0.64\";\n";
	m_str << "\tadsorptionRate = \"0.079548303\";\n";
	m_str << "}\n";
	m_str << "# 100hr options\n";
	m_str << "100hr_opts {\n";
	m_str << "\t@copyFrom \"deadFuelMoisture.defaults\";\n";
	m_str << "\tradius = \"2.0\";\n";
	m_str << "\tadsorptionRate = \"0.06\";\n";
	m_str << "}\n";
	m_str << "# 1000hr options\n";
	m_str << "1000hr_opts {\n";
	m_str << "\t@copyFrom \"deadFuelMoisture.defaults\";\n";
	m_str << "\tradius = \"3.81\";\n";
	m_str << "\tadsorptionRate = \"0.06\";\n";
	m_str << "}";
}





NFDRSInitConfig::~NFDRSInitConfig()
{
	// Nothing to do
}


