//----------------------------------------------------------------------
// WARNING: This file was generated by config2cpp. Do not edit.
//----------------------------------------------------------------------

#include "RunNFDRSConfig.h"





RunNFDRSConfig::RunNFDRSConfig()
{
	m_schema[0] = "allOutputsFile = string";
	m_schema[1] = "fuelMoisturesOutputFile = string";
	m_schema[2] = "indexOutputFile = string";
	m_schema[3] = "initFile = string";
	m_schema[4] = "loadFromStateFile = string";
	m_schema[5] = "outputInterval = int";
	m_schema[6] = "saveToStateFile = string";
	m_schema[7] = "wxFile = string";
	m_schema[8] = 0;

	m_str << "# Sample RunNFDRS configuration file\n";
	m_str << "# required to initialize RunNFDRS program\n";
	m_str << "# used by config2cpp.exe as follows:\n";
	m_str << "# config2cpp -cfg RunNFDRSSample.txt -class RunNFD";
	m_str << "RSConfig\n";
	m_str << "# NOTE short paths are used here, use of complete ";
	m_str << "paths is recommended but not required\n";
	m_str << "initFile = \"/NFDRSInitSample.txt\";\n";
	m_str << "# required as input for processing\n";
	m_str << "wxFile = \"/someWx.fw21\";\n";
	m_str << "#NFDRSState saving and loading capabilities (optio";
	m_str << "nal)\n";
	m_str << "#loadFromState will load the state file and begin ";
	m_str << "any calculations from the saved state\n";
	m_str << "loadFromStateFile = \"/someSavedState.nfdrs\";\n";
	m_str << "#saveToStateFile will save the state when calculat";
	m_str << "ion is complete to the indicated file\n";
	m_str << "saveToStateFile = \"/newSavedState.nfdrs\";\n";
	m_str << "# output files (csv) can be designated, otherwise ";
	m_str << "nothing is output \n";
	m_str << "# if they exist, they are appended to by the progr";
	m_str << "am\n";
	m_str << "# output files include a date/time and selected ou";
	m_str << "tputs\n";
	m_str << "#csv header is only written to the output file if ";
	m_str << "the file is being created\n";
	m_str << "#all outputs available, includes fuel moistures an";
	m_str << "d indexes\n";
	m_str << "allOutputsFile = \"/NFDRSoutput.csv\";\n";
	m_str << "#indexes only\n";
	m_str << "indexOutputFile = \"/NFDRSIndexes.csv\";\n";
	m_str << "#fuel moistures\n";
	m_str << "fuelMoisturesOutputFile = \"/NFDRSMoistures.csv\";\n";
	m_str << "#outputInterval 0 = hourly (each record), 1 = dail";
	m_str << "y (at ObsHour from NFDRSInit file)\n";
	m_str << "outputInterval = \"0\";";
}





RunNFDRSConfig::~RunNFDRSConfig()
{
	// Nothing to do
}


