//----------------------------------------------------------------------
// WARNING: This file was generated by config2cpp. Do not edit.
//
// Description: a class providing access to an embedded
//              configuration string.
//----------------------------------------------------------------------
#ifndef RunNFDRSConfig_h
#define RunNFDRSConfig_h

#include "config4cpp/Configuration.h"


class RunNFDRSConfig
{
public:
	//--------
	// Constructor and destructor.
	//--------
	RunNFDRSConfig();
	~RunNFDRSConfig();

	//--------
	// Get the configuration string
	//--------
	const char * getString()
	{
		return m_str.c_str();
	}

	//--------
	// Get the configuration's schema
	//--------
	void getSchema(const char **& schema, int & schemaSize)
	{
		schema = m_schema;
		schemaSize = 8;
	}
	const char ** getSchema() // null terminated array
	{
		return m_schema;
	}

private:
	//--------
	// Variables
	//--------
	CONFIG4CPP_NAMESPACE::StringBuffer m_str;
	const char *                       m_schema[9];

	//--------
	// The following are not implemented
	//--------
	RunNFDRSConfig & operator=(const RunNFDRSConfig &);
	RunNFDRSConfig(const RunNFDRSConfig &);
};


#endif
